# Generated by Django 4.1 on 2024-05-29 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TravelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolists',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
