# Generated by Django 4.1 on 2024-06-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinations',
            name='clear_picture',
        ),
    ]
